---
- name: Chack EC2 instance info
  hosts: all
  tasks:
    - name: Collect EC2 info
      amazon.aws.ec2_instance_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        instance_ids:
          - i-0648a5938119bcf59
      register: ec2_info

    - name: Display ec2_ifo
      ansible.builtin.debug:
#        var: ec2_info.instances[0].public_ip_address
        var: ec2_info
