---
- name: check vars for turbonomic
  hosts: all
  tasks:
#    - name: display vars
#      ansible.builtin.debug:
#        var: ec2_region
#    - name: display vars
#      ansible.builtin.debug:
#        var: instance_id
    - name: display vars
      ansible.builtin.debug:
        var: ansible_facts.os_family
      when: ansible_facts.os_family == "RedHat"
    - name: display vars
      ansible.builtin.debug:
        var: instance_type.tags.Name
      when: instance_type.tags.Host == ['Web']
