---
- name: Fix the problem of application down
  hosts: all
  tasks:
    - name: stop ratings apps
      ansible.builtin.command: "sh /home/ubuntu/stop_qotd-ratings.sh"
      
    - name: stop author apps
      ansible.builtin.command: "sh /home/ubuntu/stop_qotd-author.sh"
