---
- name: Read messages from a Turbonomic and Instana webhook and act on them
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    - ibm.instana.instana_webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Run EC2 Playbook for Virtual Machine Scale Action
      condition: event.payload.target.className == "VirtualMachine" and event.payload.actionType == "SCALE" and
        event.payload.target.environmentType == "CLOUD" and event.payload.target.discoveredBy.type == "AWS" and event.payload.target.tags.Host == ['Web']
      action:
        run_job_template:
          name: resize
          organization: Default
          job_args:
            extra_vars:
              instance_type: "{{ event['payload']['newEntity']['displayName'] }}"
              instance_id: "{{ event['payload']['target']['vendorIds'][event['payload']['target']['discoveredBy']['displayName']] }}"
              ec2_region: "{{ event['payload']['currentLocation']['vendorIds'][event['payload']['currentLocation']['discoveredBy']['displayName']] }}"

    - name: Run Fix Application Issue Playbook
      condition: event.payload.problem.problemText == "[QOTD] Erroneous call rate is too high"
      action:
        run_job_template:
          name: Start apps
          organization: Default
